env:
  browser: true
  es2021: true
extends:
  # - airbnb-base
  - eslint:recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  quotes:
    - error
    - single
    - avoidEscape: true
  no-console:
    - error
  no-empty:
    - error
  no-irregular-whitespace:
    - warn
  prettier/prettier:
    - error
    - singleQuote: true
      semi: false
      trailingComma: 'none'
  no-undef:
    - off
  'no-unused-vars':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
